### ISSUE TITLE
I just want to run the project locally. But it doesn't work. This is the error message.

### ISSUE THREAD

**Issue by ParseDark** [yemount/pose-animator#2]
hi, yemount.
I just want to run the project locally. But it doesn't work. This is the error message.
MacPro 15.6
```
Documents/pose-animator/node_modules/paper/dist/paper-full.js:17211:12: Unterminated string constant (17211:12)

  17209 | 			}
  17210 | 			if (/^(inline|both)$/.test(sourceMaps)) {
> 17211 | 				code += "\n
        | 				       ^
  17212 | 						+ self.btoa(unescape(encodeURIComponent(
  17213 | 							JSON.stringify(map))));
  17214 | 			}
```
Thanks your help.

**Comment by conradfuhrman** [comment]
This seems to be an issue with Parcel (https://github.com/parcel-bundler/parcel/issues/2408). I added  `--no-source-maps` to the watch script and was able to get it working.

**Comment by thllwg** [comment]
I made a PR (#15) that allows to run the application in a Docker container and fixes this problem.
You can build the container by running:
`docker build --pull --rm -f "Dockerfile" -t poseanimator:latest "."`
`docker run --rm -it  -p 1234:1234/tcp --device=/dev/video0:/dev/video0 poseanimator:latest`

**Comment by ParseDark** [comment]
Thanks for your response. I use the below solution and it works!

```
Open package.json
Change the paper line to:
"paper": "^0.12.1",

Then (for a later bug you will hit) while in package.json, go to the watch line and change it to:
"watch": "cross-env NODE_ENV=development parcel index.html --no-hmr --open --no-source-maps ",

The --no-source-maps is the key addition. No run
yarn
then run
yarn watch

You should be good now.
```
