### ISSUE TITLE
SVG editing: do the polylines matter? or just the circle objects?

### ISSUE THREAD

**Issue by dhtoran** [yemount/pose-animator#33]
When editing the SVG file in Inkscape, objects like wrists, elbows, etc are not linked/attached to polylines. So I need to move around both types of objects. Question: do I need to reposition also que polylines? or polylines are just as visual helper?

**Comment by dmey** [comment]
As far as I understand polylines are there as a visual aid and could be deleted. There is a bit more information about editing SVGs on [Avatar Animator](https://github.com/letmaik/avatar-animator) although it's work in progress.

**Comment by dhtoran** [comment]
Thanks!
