### ISSUE TITLE
Fails to run project locally - dependency error

### ISSUE THREAD

**Issue by UmutAlihan** [yemount/pose-animator#4]
Installing dependencies, node_modules with "yarn"
Then command "yarn watch" throws the error below:

![image](https://user-images.githubusercontent.com/16688836/81483231-44081300-9245-11ea-9fc7-34d2088d88ee.png)

-------- Error Output:
/home/uad/dev/pose-animator/static_image.js:21:23: Cannot resolve dependency 'paper'

Server running at http://localhost:1234 
🚨  /home/uad/dev/pose-animator/static_image.js:21:23: Cannot resolve dependency 'paper'
  19 | import * as facemesh_module from '@tensorflow-models/facemesh';
  20 | import * as tf from '@tensorflow/tfjs';
-> 21 | import * as paper from 'paper';
     |                       ^
  22 | import "babel-polyfill";
  23 | 
  24 | import dat from 'dat.gui';

**Comment by pablo-mayrgundter** [comment]
I had this too, and not exactly sure what I did to fix it, but started with removing the third_party/paper reference from the package.json and then "npm update" again.  Did this, along with the --no-source-maps arg to parsel, and got it running

**Comment by shyal** [comment]
@pablo-mayrgundter 

> Did this, along with the --no-source-maps arg to parse

What do you mean by that?

**Comment by pablo-mayrgundter** [comment]
> @pablo-mayrgundter
> 
> > Did this, along with the --no-source-maps arg to parse
> 
> What do you mean by that?

There's an issue in the parcel library (https://github.com/yemount/pose-animator/issues/2).  Here's the change to my package.json, after which I can run 'yarn watch' or 'yarn build' and serve up from a webserver from the dist directory.

"scripts": {
    "watch": "cross-env NODE_ENV=development parcel index.html --no-source-maps --no-hmr --open ",
    "build": "cross-env NODE_ENV=production parcel build index.html --no-source-maps --public-url ./",
    "build-camera": "cross-env NODE_ENV=production parcel build camera.html --public-url ./",
    "lint": "eslint .",
    "link-local": "yalc link"
  }

**Comment by shyal** [comment]
That works. Thank you.

**Comment by Rinum** [comment]
These steps worked for me:

1. Delete "paper" dependency row from package.json
2. Add "--no-source-maps" to package.json "watch" script like pablo-mayrgundter described above
3. Delete node_modules/paper
4. npm install paper
5. yarn watch

**Comment by pranayaryal** [comment]
@pablo-mayrgundter could you please send a pull request with your advice for the README.md file? Thanks.

**Comment by UmutAlihan** [comment]
> These steps worked for me:
> 
>     1. Delete "paper" dependency row from package.json
> 
>     2. Add "--no-source-maps" to package.json "watch" script like pablo-mayrgundter described above
> 
>     3. Delete node_modules/paper
> 
>     4. npm install paper
> 
>     5. yarn watch



Yeap, this has solved my issue as well. Thank you very much!

**Comment by Lesliesibbs** [comment]
> > These steps worked for me:
> > ```
> > 1. Delete "paper" dependency row from package.json
> > 
> > 2. Add "--no-source-maps" to package.json "watch" script like pablo-mayrgundter described above
"scripts": {
"watch": "cross-env NODE_ENV=development parcel index.html --no-source-maps --no-hmr --open ",
"build": "cross-env NODE_ENV=production parcel build index.html --no-source-maps --public-url ./",
"build-camera": "cross-env NODE_ENV=production parcel build camera.html --public-url ./",
"lint": "eslint .",
"link-local": "yalc link"
}
> > 
> > 3. Delete node_modules/paper
> > 
> > 4. npm install paper
> > 
> > 5. yarn watch
> > ```
> 
> Yeap, this has solved my issue as well. Thank you very much!
